minecraft_version=1.21.11
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.6+1.21.11
java_version=21
minecraft_dependency=1.21.11
sodium_version=mc1.21.11-0.8.7-fabric
iris_version=1.10.7+1.21.11-fabric
version_overlays=modern-1.21.4,render-1.21.5,modern-1.21.5,gui-1.21.6,modern-1.21.9
excluded_sources=com/cotii/customlights/client/mixin/ShaderInstanceAccessor.java,com/cotii/customlights/client/mixin/LightTextureAccessor.java,com/cotii/customlights/client/mixin/BlockModelMixin.java,com/cotii/customlights/client/mixin/BlockModelDeserializerMixin.java
