minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.0+26.2
java_version=25
minecraft_dependency=26.2
sodium_version=mc26.2-0.9.2-fabric
iris_version=1.11.4+26.2-fabric
version_overlays=modern-1.21.4,render-1.21.5,modern-1.21.5,gui-1.21.6,modern-1.21.9,modern-26
excluded_sources=com/cotii/customlights/client/mixin/ShaderInstanceAccessor.java,com/cotii/customlights/client/mixin/LightTextureAccessor.java,com/cotii/customlights/client/mixin/BlockModelMixin.java,com/cotii/customlights/client/mixin/BlockModelDeserializerMixin.java,com/cotii/customlights/client/mixin/CachedPerspectiveAccessor.java
