org.gradle.jvmargs=-Xmx3G
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_next=1.21.2
neoforge_version=21.1.251
java_version=21
version_overlays=

mod_id=customlights
mod_name=CustomLights
mod_version=1.0.2
mod_group_id=com.cotii
mod_authors=Cotii_
mod_license=CC0-1.0
mod_description=Client-side colored lights with shapes, atmosphere, animations and a live editor.
sodium_version=mc1.21.1-0.6.13-neoforge
iris_version=1.8.12+1.21.1-neoforge
