minecraft_version=1.21.8
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.136.1+1.21.8
java_version=21
minecraft_dependency=1.21.8
sodium_version=mc1.21.8-0.7.2-fabric
iris_version=1.9.6+1.21.8-fabric
geckolib_version=5.2.2
version_overlays=modern-1.21.4,render-1.21.5,modern-1.21.5,gui-1.21.6
excluded_sources=com/cotii/customlights/client/mixin/ShaderInstanceAccessor.java,com/cotii/customlights/client/mixin/LightTextureAccessor.java,com/cotii/customlights/client/mixin/BlockModelMixin.java,com/cotii/customlights/client/mixin/BlockModelDeserializerMixin.java
