modLoader="javafml"
loaderVersion="[2,)"
license="${mod_license}"
issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
config="customlights.client.mixins.json"

[[mixins]]
config="customlights.extra.mixins.json"

[[mixins]]
config="customlights.iris.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${loader_major},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},${minecraft_next})"
ordering="NONE"
side="CLIENT"
